#!/usr/bin/env python3
"""User-annotated RMUC 2026 terrain semantics for the regional map.

The blue-side geometry is transcribed from
``analysis/references/terrain_annotation_blue_user.png``. Red-side geometry is
generated by a 180-degree rotation around the map centre. This file deliberately
does not reuse the earlier rulebook-only tunnel registration, which was rejected
after visual review.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import sqlite3
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

from PIL import Image, ImageDraw, ImageFont

try:
    from highland_edge_cv import extract_highland_edges, write_edge_artifacts
except ModuleNotFoundError:  # Imported as analysis.terrain_crossing_points.
    from analysis.highland_edge_cv import extract_highland_edges, write_edge_artifacts


ROOT = Path(__file__).resolve().parents[1]
MAP_PATH = ROOT / "web" / "assets" / "map.webp"
ANNOTATION_PATH = ROOT / "analysis" / "references" / "terrain_annotation_blue_user.png"
OUTPUT_DIR = ROOT / "analysis" / "outputs"
DEFAULT_DB = ROOT.parent / "RMUC2026区域赛数据" / "rmuc_2026_region_dataset.sqlite"

MAP_WIDTH = 2337
MAP_HEIGHT = 1283
FIELD_WIDTH_M = 28.0
FIELD_HEIGHT_M = 15.0
MAP_HEIGHT_M = 17.0

FONT_REGULAR = Path("/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc")
FONT_BOLD = Path("/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc")

# Feature centres are in map.webp pixels after registering the user's 2336x1285
# image. The fitted transform is almost exactly x_map=x_user+4, y_map=y_user.
USER_TO_MAP_HOMOGRAPHY = (
    (0.999880290, 0.000014721, 4.040061600),
    (0.000005143, 1.000006730, -0.016981977),
    (-0.000000028, 0.000000030, 1.0),
)

CATEGORY_ZH = {
    "fly_ramp": "飞坡",
    "road_tunnel": "公路隧道",
    "road_step": "公路台阶",
    "rough_road": "起伏路段",
    "central_highland_step": "中央高地台阶",
    "highland_tunnel": "高地隧道",
    "slope_43": "43°坡",
    "trapezoid_highland_step": "梯形高地台阶",
    "central_highland_ledge_400mm": "中央高地 400 mm 高差边缘",
    "trapezoid_highland_boundary": "梯形高地边界",
    "central_highland_region": "中央高地区域",
    "trapezoid_highland_top": "梯形高地上层平台",
}


@dataclass(frozen=True)
class GateSpec:
    index: int
    category: str
    center_px: tuple[float, float]
    axis_angle_deg: float
    length_px: float
    width_px: float
    capability_tag: str
    note: str


@dataclass(frozen=True)
class Feature:
    feature_id: str
    category: str
    side: str
    kind: str
    geometry_type: str
    map_geometry_px: tuple[tuple[float, float], ...]
    center_map_px: tuple[float, float]
    source: str
    symmetry: str
    default_traversability: str
    capability_tag: str | None = None
    height_difference_m: float | None = None
    gate_index: int | None = None
    note: str = ""


# Eight physical interfaces marked on the blue side. The arrows in the user's
# image are callouts, not mandatory travel directions, so every gate is modelled
# as physically bidirectional. Boxes are telemetry tolerance zones, not CAD
# outlines of the obstacles.
BLUE_GATE_SPECS = (
    GateSpec(1, "fly_ramp", (1169, 84), 0, 190, 72, "fly_ramp_capable", "用户标注的飞坡通路。"),
    GateSpec(2, "road_tunnel", (1549, 213), 90, 120, 60, "road_tunnel_fit", "公路与中央高地之间的隧道通路。"),
    GateSpec(3, "road_step", (1642, 213), 90, 120, 60, "road_step_capable", "与公路隧道并列的公路台阶。"),
    GateSpec(4, "rough_road", (1853, 127), 0, 170, 90, "rough_terrain_capable", "起伏路段的轨迹检测区。"),
    GateSpec(5, "central_highland_step", (1532, 645), 0, 190, 240, "central_highland_step_capable", "中央高地边缘最凸出的常规台阶跨越点；纵向宽度取中央高地内部白色竖线的 OpenCV 检测长度。"),
    GateSpec(6, "highland_tunnel", (1178, 1118), 0, 180, 66, "highland_tunnel_fit", "中央高地下方隧道通路。"),
    GateSpec(7, "slope_43", (2004, 860), 90, 165, 64, "slope_43_capable", "通往梯形高地上层平台的 43° 坡。"),
    GateSpec(8, "trapezoid_highland_step", (2004, 1017), 90, 125, 64, "trapezoid_step_capable", "梯形高地上层平台的台阶入口。"),
)

# The cyan outline around the R-marked top platform on the blue trapezoid
# highland. It is retained as a region so the 43° ramp and lower step can be
# associated with the same destination surface.
BLUE_TRAPEZOID_TOP = (
    (1931, 857), (2058, 857), (2058, 1016),
    (1847, 1017), (1876, 949), (1909, 904),
)


def rotate_point_180(point: tuple[float, float]) -> tuple[float, float]:
    """Rotate a map pixel around the exact image centre."""
    return MAP_WIDTH - 1 - point[0], MAP_HEIGHT - 1 - point[1]


def rotate_geometry_180(
    geometry: Sequence[tuple[float, float]],
) -> tuple[tuple[float, float], ...]:
    return tuple(rotate_point_180(point) for point in geometry)


def oriented_box(
    center: tuple[float, float], angle_deg: float, length: float, width: float,
) -> tuple[tuple[float, float], ...]:
    angle = math.radians(angle_deg)
    ux, uy = math.cos(angle), math.sin(angle)
    vx, vy = -uy, ux
    half_length, half_width = length / 2, width / 2
    cx, cy = center
    return tuple(
        (
            cx + along * half_length * ux + across * half_width * vx,
            cy + along * half_length * uy + across * half_width * vy,
        )
        for along, across in ((-1, -1), (1, -1), (1, 1), (-1, 1))
    )


def polygon_center(points: Sequence[tuple[float, float]]) -> tuple[float, float]:
    return (
        sum(point[0] for point in points) / len(points),
        sum(point[1] for point in points) / len(points),
    )


def map_to_field(x_px: float, y_px: float) -> tuple[float, float]:
    """Match web/app.js: map is 28x17 m with 1 m vertical padding."""
    x_m = x_px / MAP_WIDTH * FIELD_WIDTH_M
    y_m = 16.0 - y_px / MAP_HEIGHT * MAP_HEIGHT_M
    return (
        max(0.0, min(FIELD_WIDTH_M, x_m)),
        max(0.0, min(FIELD_HEIGHT_M, y_m)),
    )


def field_to_map(x_m: float, y_m: float) -> tuple[float, float]:
    return (
        x_m / FIELD_WIDTH_M * MAP_WIDTH,
        (16.0 - y_m) / MAP_HEIGHT_M * MAP_HEIGHT,
    )


def build_features() -> tuple[Feature, ...]:
    features: list[Feature] = []
    edge_data = extract_highland_edges(MAP_PATH)
    blue_ledges = {
        name: tuple(tuple(point) for point in segment["raw_path_px"])
        for name, segment in edge_data["segments"].items()
    }
    for spec in BLUE_GATE_SPECS:
        width_px = spec.width_px
        if spec.category == "central_highland_step":
            width_px = edge_data["reference_lines"]["central_highland_inner_vertical"]["length_px"]
        blue_geometry = oriented_box(
            spec.center_px, spec.axis_angle_deg, spec.length_px, width_px,
        )
        for side in ("blue", "red"):
            if side == "blue":
                center = spec.center_px
                geometry = blue_geometry
                source = "user_annotation"
                symmetry = "blue_direct"
            else:
                center = rotate_point_180(spec.center_px)
                geometry = rotate_geometry_180(blue_geometry)
                source = "user_annotation_derived"
                symmetry = "red_180_rotated_from_blue"
            features.append(
                Feature(
                    feature_id=f"{side}_{spec.category}",
                    category=spec.category,
                    side=side,
                    kind="crossing_gate",
                    geometry_type="polygon",
                    map_geometry_px=geometry,
                    center_map_px=center,
                    source=source,
                    symmetry=symmetry,
                    default_traversability="vehicle_dependent",
                    capability_tag=spec.capability_tag,
                    gate_index=spec.index,
                    note=spec.note + " 可物理双向通行；标注箭头不代表规则强制方向。",
                )
            )

    blue_trapezoid_boundary = tuple(
        tuple(point) for point in edge_data["trapezoid_boundary"]["raw_path_px"]
    )
    for side in ("blue", "red"):
        geometry = (
            blue_trapezoid_boundary
            if side == "blue"
            else rotate_geometry_180(blue_trapezoid_boundary)
        )
        features.append(
            Feature(
                feature_id=f"{side}_trapezoid_highland_boundary",
                category="trapezoid_highland_boundary",
                side=side,
                kind="terrain_boundary",
                geometry_type="polyline",
                map_geometry_px=geometry,
                center_map_px=polygon_center(geometry),
                source=(
                    "user_annotation_opencv_canny_hough"
                    if side == "blue"
                    else "user_annotation_opencv_canny_hough_180_rotated"
                ),
                symmetry="blue_direct" if side == "blue" else "red_180_rotated_from_blue",
                default_traversability="boundary_requires_crossing_capability",
                note="梯形高地边界仅限 B7/B8 周围的小平台；不包含左侧长斜坡和道路边界。应与 43° 坡和梯形高地台阶入口分开建模。",
            )
        )

    for side, symmetry in (("blue", "blue_direct"), ("red", "red_180_rotated_from_blue")):
        for part, blue_line in blue_ledges.items():
            geometry = blue_line if side == "blue" else rotate_geometry_180(blue_line)
            features.append(
                Feature(
                    feature_id=f"{side}_central_highland_ledge_400mm_{part}",
                    category="central_highland_ledge_400mm",
                    side=side,
                    kind="conditional_ledge",
                    geometry_type="polyline",
                    map_geometry_px=geometry,
                    center_map_px=polygon_center(geometry),
                    source=(
                        "user_annotation_opencv_edge"
                        if side == "blue"
                        else "user_annotation_opencv_edge_180_rotated"
                    ),
                    symmetry=symmetry,
                    default_traversability="blocked_by_default",
                    capability_tag="jump_capable",
                    height_difference_m=0.4,
                    note="用户确认为约 400 mm 高差；边界由 OpenCV 在原图上吸附提取。大部分学校不能直接上，仅对已确认具备跳跃能力的机器人开放。",
                )
            )

    blue_boundary = blue_ledges["north"] + ((1559, 645),) + blue_ledges["south"]
    red_boundary = rotate_geometry_180(blue_boundary)
    central_polygon = blue_boundary + (red_boundary[0],) + red_boundary + (blue_boundary[0],)
    features.append(
        Feature(
            feature_id="central_highland_region",
            category="central_highland_region",
            side="neutral",
            kind="terrain_region",
            geometry_type="polygon",
            map_geometry_px=central_polygon,
            center_map_px=polygon_center(central_polygon),
            source="user_annotation_and_symmetry",
            symmetry="assembled_from_blue_and_red_edges",
            default_traversability="surface_passable_after_entry",
            note="中央高地顶面区域；进入方式需另看台阶、隧道或 jump_capable 高差跨越。",
        )
    )

    for side in ("blue", "red"):
        geometry = BLUE_TRAPEZOID_TOP if side == "blue" else rotate_geometry_180(BLUE_TRAPEZOID_TOP)
        features.append(
            Feature(
                feature_id=f"{side}_trapezoid_highland_top",
                category="trapezoid_highland_top",
                side=side,
                kind="terrain_region",
                geometry_type="polygon",
                map_geometry_px=geometry,
                center_map_px=polygon_center(geometry),
                source="user_annotation" if side == "blue" else "user_annotation_derived",
                symmetry="blue_direct" if side == "blue" else "red_180_rotated_from_blue",
                default_traversability="surface_passable_after_entry",
                note="用户圈出的梯形高地上层平台；与 43° 坡和梯形高地台阶关联。",
            )
        )
    return tuple(features)


def point_in_polygon(x: float, y: float, polygon: Sequence[tuple[float, float]]) -> bool:
    inside = False
    previous = len(polygon) - 1
    for current, (current_x, current_y) in enumerate(polygon):
        previous_x, previous_y = polygon[previous]
        if (current_y > y) != (previous_y > y):
            at_x = (previous_x - current_x) * (y - current_y) / (previous_y - current_y) + current_x
            if x < at_x:
                inside = not inside
        previous = current
    return inside


def distance_to_segment(
    point: tuple[float, float], start: tuple[float, float], end: tuple[float, float],
) -> float:
    x, y = point
    sx, sy = start
    ex, ey = end
    dx, dy = ex - sx, ey - sy
    if dx == 0 and dy == 0:
        return math.hypot(x - sx, y - sy)
    ratio = max(0.0, min(1.0, ((x - sx) * dx + (y - sy) * dy) / (dx * dx + dy * dy)))
    return math.hypot(x - (sx + ratio * dx), y - (sy + ratio * dy))


def geometry_distance(
    point: tuple[float, float], geometry: Sequence[tuple[float, float]], geometry_type: str,
) -> float:
    if geometry_type == "polygon" and point_in_polygon(*point, geometry):
        return 0.0
    pairs = list(zip(geometry, geometry[1:]))
    if geometry_type == "polygon":
        pairs.append((geometry[-1], geometry[0]))
    return min(distance_to_segment(point, start, end) for start, end in pairs)


def _orientation(a: tuple[float, float], b: tuple[float, float], c: tuple[float, float]) -> float:
    return (b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0])


def segments_intersect(
    a: tuple[float, float], b: tuple[float, float],
    c: tuple[float, float], d: tuple[float, float],
) -> bool:
    o1, o2 = _orientation(a, b, c), _orientation(a, b, d)
    o3, o4 = _orientation(c, d, a), _orientation(c, d, b)
    epsilon = 1e-9
    if abs(o1) < epsilon and distance_to_segment(c, a, b) < epsilon:
        return True
    if abs(o2) < epsilon and distance_to_segment(d, a, b) < epsilon:
        return True
    if abs(o3) < epsilon and distance_to_segment(a, c, d) < epsilon:
        return True
    if abs(o4) < epsilon and distance_to_segment(b, c, d) < epsilon:
        return True
    return (o1 > 0) != (o2 > 0) and (o3 > 0) != (o4 > 0)


def segment_hits_feature(
    start: tuple[float, float], end: tuple[float, float], feature: Feature,
) -> bool:
    geometry = feature.map_geometry_px
    if feature.geometry_type == "polygon" and (
        point_in_polygon(*start, geometry) or point_in_polygon(*end, geometry)
    ):
        return True
    pairs = list(zip(geometry, geometry[1:]))
    if feature.geometry_type == "polygon":
        pairs.append((geometry[-1], geometry[0]))
    return any(segments_intersect(start, end, a, b) for a, b in pairs)


def feature_to_dict(feature: Feature) -> dict:
    field_geometry = tuple(map_to_field(x, y) for x, y in feature.map_geometry_px)
    center_field = map_to_field(*feature.center_map_px)
    return {
        "feature_id": feature.feature_id,
        "category": feature.category,
        "category_zh": CATEGORY_ZH[feature.category],
        "side": feature.side,
        "kind": feature.kind,
        "geometry_type": feature.geometry_type,
        "gate_index": feature.gate_index,
        "source": feature.source,
        "symmetry": feature.symmetry,
        "default_traversability": feature.default_traversability,
        "capability_tag": feature.capability_tag,
        "height_difference_m": feature.height_difference_m,
        "physical_direction": "bidirectional" if feature.kind != "terrain_region" else None,
        "center_map_px": [round(value, 3) for value in feature.center_map_px],
        "center_field_m": [round(value, 4) for value in center_field],
        "map_geometry_px": [[round(x, 3), round(y, 3)] for x, y in feature.map_geometry_px],
        "field_geometry_m": [[round(x, 4), round(y, 4)] for x, y in field_geometry],
        "note": feature.note,
    }


def detect_features(
    x_m: float,
    y_m: float,
    features: Sequence[Feature] | None = None,
    padding_m: float = 0.30,
    kinds: Iterable[str] = ("crossing_gate", "conditional_ledge", "terrain_boundary"),
) -> list[dict]:
    """Return physical features near a telemetry point in field metres."""
    features = features or build_features()
    allowed_kinds = set(kinds)
    point_px = field_to_map(x_m, y_m)
    # Convert a field-metre tolerance to an isotropic map-pixel approximation.
    padding_px = padding_m * ((MAP_WIDTH / FIELD_WIDTH_M + MAP_HEIGHT / MAP_HEIGHT_M) / 2)
    result = []
    for feature in features:
        if feature.kind not in allowed_kinds:
            continue
        distance_px = geometry_distance(point_px, feature.map_geometry_px, feature.geometry_type)
        if distance_px <= padding_px:
            result.append(
                {
                    "feature_id": feature.feature_id,
                    "category": feature.category,
                    "category_zh": CATEGORY_ZH[feature.category],
                    "side": feature.side,
                    "kind": feature.kind,
                    "distance_m_approx": round(distance_px / (MAP_WIDTH / FIELD_WIDTH_M), 4),
                    "default_traversability": feature.default_traversability,
                    "capability_tag": feature.capability_tag,
                }
            )
    return sorted(result, key=lambda item: item["distance_m_approx"])


def classify_transition(
    previous_x_m: float,
    previous_y_m: float,
    x_m: float,
    y_m: float,
    capabilities: Iterable[str] = (),
    features: Sequence[Feature] | None = None,
) -> list[dict]:
    """Classify a movement segment that intersects a crossing gate or ledge."""
    features = features or build_features()
    capabilities = set(capabilities)
    start, end = field_to_map(previous_x_m, previous_y_m), field_to_map(x_m, y_m)
    hits = []
    for feature in features:
        if feature.kind not in ("crossing_gate", "conditional_ledge", "terrain_boundary"):
            continue
        if not segment_hits_feature(start, end, feature):
            continue
        if feature.kind == "conditional_ledge":
            allowed: bool | None = feature.capability_tag in capabilities
        else:
            allowed = None  # Vehicle-specific; learn/label this from observed teams.
        hits.append(
            {
                "feature_id": feature.feature_id,
                "category": feature.category,
                "category_zh": CATEGORY_ZH[feature.category],
                "side": feature.side,
                "allowed": allowed,
                "required_capability": feature.capability_tag,
                "reason": (
                    "400 mm ledge requires jump_capable"
                    if feature.kind == "conditional_ledge"
                    else "terrain boundary requires a designated gate or vehicle-specific capability"
                    if feature.kind == "terrain_boundary"
                    else "vehicle-specific physical interface"
                ),
            }
        )
    return hits


def event_counts(db_path: Path) -> dict[str, int]:
    if not db_path.exists():
        return {}
    connection = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    rows = connection.execute(
        "SELECT 类别, COUNT(*) FROM events WHERE 类别 IN ('过中央高地','台阶跨越','飞坡') GROUP BY 类别"
    ).fetchall()
    connection.close()
    return {str(category): int(count) for category, count in rows}


def font(path: Path, size: int) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(str(path), size=size, index=0)


def draw_centered_label(
    draw: ImageDraw.ImageDraw,
    center: tuple[float, float],
    text: str,
    text_font: ImageFont.FreeTypeFont,
    outline: tuple[int, int, int, int],
) -> None:
    box = draw.textbbox((0, 0), text, font=text_font, stroke_width=0)
    width, height = box[2] - box[0] + 16, box[3] - box[1] + 10
    x, y = center
    draw.rounded_rectangle(
        (x - width / 2, y - height / 2, x + width / 2, y + height / 2),
        radius=8,
        fill=(7, 13, 20, 235),
        outline=outline,
        width=3,
    )
    draw.text(
        (x - (box[2] - box[0]) / 2, y - (box[3] - box[1]) / 2 - box[1]),
        text,
        font=text_font,
        fill="white",
    )


def draw_dashed_polyline(
    draw: ImageDraw.ImageDraw,
    points: Sequence[tuple[float, float]],
    fill: tuple[int, int, int, int],
    width: int = 8,
    dash: float = 20,
    gap: float = 12,
) -> None:
    drawing = True
    remaining = dash
    for start, end in zip(points, points[1:]):
        dx, dy = end[0] - start[0], end[1] - start[1]
        length = math.hypot(dx, dy)
        if not length:
            continue
        position = 0.0
        while position < length:
            step = min(remaining, length - position)
            finish = position + step
            if drawing:
                a = (start[0] + dx * position / length, start[1] + dy * position / length)
                b = (start[0] + dx * finish / length, start[1] + dy * finish / length)
                draw.line((a, b), fill=fill, width=width)
            position = finish
            remaining -= step
            if remaining <= 1e-9:
                drawing = not drawing
                remaining = dash if drawing else gap


def render_map(features: Sequence[Feature], output_path: Path) -> None:
    source = Image.open(MAP_PATH).convert("RGBA")
    if source.size != (MAP_WIDTH, MAP_HEIGHT):
        raise ValueError(f"unexpected map dimensions: {source.size}")

    panel_height = 485
    canvas = Image.new("RGBA", (MAP_WIDTH, MAP_HEIGHT + panel_height), "#10161d")
    canvas.alpha_composite(source, (0, 0))
    overlay = Image.new("RGBA", source.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)

    for feature in features:
        points = [(round(x), round(y)) for x, y in feature.map_geometry_px]
        if feature.category == "central_highland_region":
            draw.polygon(points, fill=(171, 109, 255, 28), outline=(196, 151, 255, 150), width=3)
        elif feature.category == "trapezoid_highland_top":
            draw.polygon(points, fill=(255, 205, 77, 32), outline=(255, 210, 91, 175), width=4)

    for feature in features:
        if feature.kind == "conditional_ledge":
            draw_dashed_polyline(draw, feature.map_geometry_px, (255, 154, 61, 255))
        elif feature.kind == "terrain_boundary":
            draw_dashed_polyline(draw, feature.map_geometry_px, (255, 218, 73, 255), width=7)

    side_color = {"blue": (0, 180, 255, 105), "red": (255, 74, 93, 105)}
    side_outline = {"blue": (65, 202, 255, 255), "red": (255, 101, 116, 255)}
    for feature in features:
        if feature.kind != "crossing_gate":
            continue
        points = [(round(x), round(y)) for x, y in feature.map_geometry_px]
        draw.polygon(points, fill=side_color[feature.side], outline=side_outline[feature.side], width=5)

    canvas.alpha_composite(overlay, (0, 0))
    draw = ImageDraw.Draw(canvas)
    code_font = font(FONT_BOLD, 22)
    title_font = font(FONT_BOLD, 31)
    body_font = font(FONT_REGULAR, 23)
    note_font = font(FONT_REGULAR, 20)
    strong_font = font(FONT_BOLD, 22)

    for feature in features:
        if feature.kind == "crossing_gate":
            prefix = "B" if feature.side == "blue" else "R"
            draw_centered_label(
                draw,
                feature.center_map_px,
                f"{prefix}{feature.gate_index}",
                code_font,
                side_outline[feature.side],
            )

    draw_centered_label(draw, (1588, 520), "400mm", code_font, (255, 154, 61, 255))
    draw_centered_label(draw, rotate_point_180((1588, 520)), "400mm", code_font, (255, 154, 61, 255))

    panel_y = MAP_HEIGHT
    draw.rectangle((0, panel_y, MAP_WIDTH, panel_y + panel_height), fill="#10161d")
    draw.rectangle((0, panel_y, MAP_WIDTH, panel_y + 4), fill="#354352")
    draw.text((40, panel_y + 18), "RMUC 2026 地形跨越语义 · OpenCV 精确边缘 V4", font=title_font, fill="white")
    draw.text(
        (40, panel_y + 61),
        "B = 蓝方原标注；R = 绕场地中心 180° 对称。半透明矩形是轨迹容差区，不是设施 CAD 边界。",
        font=note_font,
        fill="#b9c7d4",
    )

    descriptions = tuple((spec.index, CATEGORY_ZH[spec.category], spec.note) for spec in BLUE_GATE_SPECS)
    for index, name, description in descriptions:
        column = 0 if index <= 4 else 1
        row = (index - 1) % 4
        x = 42 + column * 1150
        y = panel_y + 105 + row * 61
        color = (65, 202, 255, 255)
        draw.rounded_rectangle((x, y, x + 52, y + 37), radius=17, fill=(16, 30, 42, 255), outline=color, width=3)
        draw.text((x + 12, y + 2), str(index), font=strong_font, fill="white")
        draw.text((x + 68, y + 1), name, font=strong_font, fill="#eef5fb")
        draw.text((x + 265, y + 3), description, font=note_font, fill="#c8d3dd")

    draw.text(
        (42, panel_y + 363),
        "橙色虚线 = 中央高地其余边缘约 400 mm 高差：默认不可直接通行，只对已确认 jump_capable 的机器人视为候选跳跃通路。",
        font=strong_font,
        fill="#ffba76",
    )
    draw.text(
        (42, panel_y + 400),
        "黄色虚线 = 仅围绕 B7/B8 的小块梯形高地；左侧长斜坡/道路边界已排除。",
        font=strong_font,
        fill="#ffe782",
    )
    draw.text(
        (42, panel_y + 442),
        "中央高地常规台阶仅为 5 号点（边缘最凸出处）；箭头仅是用户标注指向，本数据不将其解释为强制行驶方向。",
        font=note_font,
        fill="#b9c7d4",
    )
    canvas.convert("RGB").save(output_path, "PNG", optimize=True)


def write_outputs(features: Sequence[Feature], counts: dict[str, int]) -> tuple[Path, ...]:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    png_path = OUTPUT_DIR / "terrain_semantics_user_annotated.png"
    json_path = OUTPUT_DIR / "terrain_semantics_user_annotated.json"
    csv_path = OUTPUT_DIR / "terrain_semantics_user_annotated.csv"
    md_path = OUTPUT_DIR / "terrain_semantics_user_annotated.md"

    render_map(features, png_path)
    edge_data = extract_highland_edges(MAP_PATH)
    edge_json_path, edge_debug_path = write_edge_artifacts(edge_data)
    blue_b5 = next(feature for feature in features if feature.feature_id == "blue_central_highland_step")
    b5_xs = [point[0] for point in blue_b5.map_geometry_px]
    b5_ys = [point[1] for point in blue_b5.map_geometry_px]
    b5_size = [round(max(b5_xs) - min(b5_xs)), round(max(b5_ys) - min(b5_ys))]
    payload = {
        "schema_version": 3,
        "status": "user_annotation_ground_truth_v4_small_trapezoid_highland",
        "map_asset": str(MAP_PATH.relative_to(ROOT)),
        "annotation_asset": str(ANNOTATION_PATH.relative_to(ROOT)),
        "map_size_px": [MAP_WIDTH, MAP_HEIGHT],
        "field_size_m": [FIELD_WIDTH_M, FIELD_HEIGHT_M],
        "coordinate_mapping": {
            "x_m": "x_px / 2337 * 28",
            "y_m": "16 - y_px / 1283 * 17, clamped to [0,15]",
            "compatible_with": "web/app.js mapPoint()",
        },
        "annotation_registration": {
            "user_image_size_px": [2336, 1285],
            "homography_user_image_to_map": USER_TO_MAP_HOMOGRAPHY,
            "feature_centres": "manually transcribed from user cyan callouts after registration",
            "central_highland_edges": "OpenCV fitted to original map pixels inside the user-annotated search corridor",
        },
        "edge_extraction": {
            "artifact": str(edge_json_path.relative_to(ROOT)),
            "debug_overlay": str(edge_debug_path.relative_to(ROOT)),
            "algorithm": edge_data["algorithm"],
            "opencv_version": edge_data["opencv_version"],
            "parameters": edge_data["parameters"],
        },
        "symmetry": {
            "operation": "180_degree_rotation",
            "pixel_formula": ["x_red = 2336 - x_blue", "y_red = 1282 - y_blue"],
            "centre_px": [(MAP_WIDTH - 1) / 2, (MAP_HEIGHT - 1) / 2],
        },
        "semantics": {
            "annotation_arrows": "location callouts only; no mandatory travel direction inferred",
            "central_highland_step": "only the most protruding point of the central highland edge",
            "other_central_highland_edge": "approximately 400 mm ledge, blocked by default",
            "jump_exception": "only robots/teams positively labelled jump_capable may use the 400 mm ledge as a candidate route",
            "gate_boxes": "telemetry tolerance zones, not physical CAD footprints",
            "b5_r5_tolerance_px": b5_size,
            "b5_r5_width_source": "OpenCV Hough length of the central-highland internal white vertical line",
            "trapezoid_highland_boundary": "small platform around B7/B8 only; long road/slope boundary explicitly excluded",
        },
        "regional_event_counts_for_later_validation": counts,
        "features": [feature_to_dict(feature) for feature in features],
    }
    json_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    fieldnames = (
        "feature_id", "category", "category_zh", "side", "kind", "geometry_type",
        "gate_index", "source", "symmetry", "default_traversability", "capability_tag",
        "height_difference_m", "center_x_m", "center_y_m", "center_x_px", "center_y_px",
        "field_geometry_m", "note",
    )
    with csv_path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for feature in features:
            data = feature_to_dict(feature)
            writer.writerow(
                {
                    **{key: data[key] for key in fieldnames if key in data},
                    "center_x_m": data["center_field_m"][0],
                    "center_y_m": data["center_field_m"][1],
                    "center_x_px": data["center_map_px"][0],
                    "center_y_px": data["center_map_px"][1],
                    "field_geometry_m": json.dumps(data["field_geometry_m"], ensure_ascii=False),
                }
            )

    lines = [
        "# RMUC 2026 地形跨越语义（OpenCV 精确边缘 V4）",
        "",
        "蓝方语义来自用户 P 图，中央高地边缘在用户描边走廊内由 OpenCV 吸附到原图像素；红方按场地中心 180° 对称生成。",
        "",
        "| 编号 | 蓝方 ID | 红方 ID | 地形 | 蓝方中心 (m) | 能力标签 |",
        "| ---: | --- | --- | --- | --- | --- |",
    ]
    by_id = {feature.feature_id: feature for feature in features}
    for spec in BLUE_GATE_SPECS:
        blue = by_id[f"blue_{spec.category}"]
        x_m, y_m = map_to_field(*blue.center_map_px)
        lines.append(
            f"| {spec.index} | `blue_{spec.category}` | `red_{spec.category}` | "
            f"{CATEGORY_ZH[spec.category]} | ({x_m:.3f}, {y_m:.3f}) | `{spec.capability_tag}` |"
        )
    lines.extend(
        [
            "",
            "## 中央高地高差口径",
            "",
            "- 常规高地台阶只是编号 5，即中央高地边缘最凸出处。",
            f"- B5/R5 轨迹容差区为 {b5_size[0]}×{b5_size[1]} 地图像素；纵向宽度来自中央高地内部白色竖线的 Hough 检测长度。",
            "- 橙色虚线所示其余边缘为约 400 mm 高差，默认不可直接通行。",
            "- 精确边缘原始逐行点和算法参数见 `terrain_highland_edges_cv.json`。",
            "- 梯形高地仅是 B7/B8 周围的小平台；左侧长斜坡和道路边界明确排除。",
            "- 该小平台边界作为 `terrain_boundary` 独立存储，不与 43° 坡或梯形高地台阶混合。",
            "- 仅当队伍/机器人已被独立证据标记为 `jump_capable` 时，才把该边缘当作候选跳跃路线。",
            "",
            "## 代码接口",
            "",
            "- `detect_features(x_m, y_m, padding_m=0.30)`：查询轨迹点附近的跨越接口/高差边缘。",
            "- `classify_transition(prev_x, prev_y, x, y, capabilities=...)`：判定一段移动是否穿过接口或 400 mm 边缘。",
            "- 轨迹容差矩形用于清洗定位噪声，不应解释为设施尺寸。",
            "",
        ]
    )
    md_path.write_text("\n".join(lines), encoding="utf-8")
    return png_path, json_path, csv_path, md_path, edge_json_path, edge_debug_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", type=Path, default=DEFAULT_DB)
    parser.add_argument("--x", type=float, help="query field x in metres")
    parser.add_argument("--y", type=float, help="query field y in metres")
    parser.add_argument("--padding", type=float, default=0.30)
    parser.add_argument("--prev-x", type=float)
    parser.add_argument("--prev-y", type=float)
    parser.add_argument("--capability", action="append", default=[])
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    features = build_features()
    paths = write_outputs(features, event_counts(args.db))
    for path in paths:
        print(path)

    query_values = (args.x, args.y)
    if (args.x is None) != (args.y is None):
        raise SystemExit("--x and --y must be supplied together")
    transition_values = (args.prev_x, args.prev_y, args.x, args.y)
    supplied = [value is not None for value in transition_values]
    if any(supplied) and not all(supplied) and args.prev_x is not None:
        raise SystemExit("--prev-x, --prev-y, --x and --y must be supplied together")
    if all(value is not None for value in transition_values):
        result = classify_transition(*transition_values, capabilities=args.capability, features=features)
        print(json.dumps(result, ensure_ascii=False, indent=2))
    elif all(value is not None for value in query_values):
        result = detect_features(args.x, args.y, features, args.padding)
        print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
